# csv_basics.py

"""
Definition: The 'csv' module implements classes to read and write tabular data in CSV format. 
It allows programmers to say, "write this data in the format preferred by Excel," or "read data from this file which was generated by Excel."
"""

import csv
import os

def demo_csv():
    filename = "data.csv"
    data = [
        ["Name", "Age", "City"],
        ["Kunal", "20", "Mumbai"],
        ["Alice", "25", "New York"]
    ]
    
    # Writing CSV
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(data)
    print(f"CSV file '{filename}' created.")
    
    # Reading CSV
    with open(filename, "r") as f:
        reader = csv.reader(f)
        print("Reading CSV data:")
        for row in reader:
            print(f"  {row}")
            
    # Cleanup
    os.remove(filename)

demo_csv()
